version: '3'

volumes:
  db-store:
    driver: local

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  db:
    container_name: mysql8
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/logs:/var/log/mysql
      - ./docker/db/etc/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - 3306:3306
  php:
    container_name: php
    links:
      - db
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    command: php /var/www/artisan serve --host 0.0.0.0  --port=9000
    ports:
      - "9000:9000"
    volumes:
      - ${PROJECT_PATH}/app:/var/www:cached
      - ./php/etc/php.ini:/usr/local/etc/php/php.ini
      - ./logs:/var/log